name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: "unique"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create work space
        run: mkdir -p ${{ vars.BASE_DIR }}

      - name: Update LLVM
        run: ./update-llvm.sh
        working-directory: ${{ vars.BASE_DIR }}

      - name: Update llvm-test-suite
        run: ./update-llvm-test-suite.sh
        working-directory: ${{ vars.BASE_DIR }}

      - name: Build LLVM
        run: ./build-llvm.sh
        working-directory: ${{ vars.BASE_DIR }}
