name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: https://github.com/llvm/llvm-project
          path: llvm-project
      
      - uses: actions/checkout@v3
        with:
          repository: https://github.com/llvm/llvm-test-suite
          path: llvm-test-suite 

      - name: Build LLVM
        run: ./build.sh
