name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          path: llvm-project
          fetch-depth: 0
      
      - uses: actions/checkout@v3
        with:
          repository: llvm/llvm-test-suite
          path: llvm-test-suite
          fetch-depth: 0

      - name: Cache llvm-build
        id: llvm-build
        uses: khj809/github-action-cache-local-fs@v1
        with:
          path: llvm-build
          key: llvm-build
          cache-base-path: /tmp/cache

      - name: Build LLVM
        run: ./build.sh
